import { COLORS } from "./colors";
import { GAME_VISUALS } from "./visuals";

export const createDefaultParty = () => [
  {
    id: "phetto",
    name: "เพชรโตะ",
    nameEn: "PHETTO",
    cls: "WARRIOR",
    color: COLORS.gold,
    e: "[W]",
    portrait: GAME_VISUALS.portraits.phetto,
    sprite: GAME_VISUALS.portraits.phetto,
    hp: 120,
    mxHp: 120,
    mp: 40,
    mxMp: 40,
    atk: 28,
    def: 14,
    lv: 1,
    alive: true,
    buf: 0,
    bufT: 0,
    defending: false,
    wName: "Iron Sword",
    wLv: 1,
    skills: [
      {
        name: "SLASH",
        mp: 0,
        mult: 1.3,
        type: "atk",
        tar: "one",
        desc: "ฟันดาบอย่างหนักหน่วง\n//Powerful sword slash",
      },
      {
        name: "SHIELD BASH",
        mp: 8,
        mult: 0.9,
        type: "atk",
        tar: "one",
        stun: true,
        desc: "โจมตีและทำให้ชะงัก 1 เทิร์น\n//Attack + stun 1 turn",
      },
      {
        name: "WAR CRY",
        mp: 14,
        mult: 0,
        type: "buff",
        tar: "party",
        bufAmt: 8,
        bufT: 3,
        desc: "เพิ่ม ATK ทั้งทีม +8 เป็นเวลา 3 เทิร์น\n//Party ATK +8 for 3 turns",
      },
    ],
  },
  {
    id: "lyra",
    name: "ลีร่า",
    nameEn: "LYRA",
    cls: "MAGE",
    color: COLORS.purple,
    e: "[M]",
    portrait: GAME_VISUALS.portraits.lyra,
    sprite: GAME_VISUALS.portraits.lyra,
    hp: 75,
    mxHp: 75,
    mp: 100,
    mxMp: 100,
    atk: 36,
    def: 6,
    lv: 1,
    alive: true,
    buf: 0,
    bufT: 0,
    defending: false,
    wName: "Oak Staff",
    wLv: 1,
    skills: [
      {
        name: "FIREBALL",
        mp: 12,
        mult: 1.6,
        type: "atk",
        tar: "one",
        desc: "ปล่อยเปลวไฟเวทมนตร์\n//Magical fire blast",
      },
      {
        name: "BLIZZARD",
        mp: 20,
        mult: 1.1,
        type: "atk",
        tar: "all",
        desc: "เวทน้ำแข็งโจมตีศัตรูทั้งหมด\n//Ice magic — all enemies",
      },
      {
        name: "HEAL",
        mp: 15,
        mult: 0,
        type: "heal",
        tar: "ally",
        healAmt: 55,
        desc: "ฟื้นฟู HP ให้พันธมิตร 55\n//Restore 55 HP to ally",
      },
    ],
  },
  {
    id: "riven",
    name: "ริเวน",
    nameEn: "RIVEN",
    cls: "ARCHER",
    color: COLORS.green,
    e: "[A]",
    portrait: GAME_VISUALS.portraits.riven,
    sprite: GAME_VISUALS.portraits.riven,
    hp: 95,
    mxHp: 95,
    mp: 50,
    mxMp: 50,
    atk: 30,
    def: 10,
    lv: 1,
    alive: true,
    buf: 0,
    bufT: 0,
    defending: false,
    wName: "Ash Bow",
    wLv: 1,
    skills: [
      {
        name: "AIMED SHOT",
        mp: 0,
        mult: 1.25,
        type: "atk",
        tar: "one",
        desc: "ยิงธนูเจาะจุดอ่อน\n//Precise piercing shot",
      },
      {
        name: "ARROW RAIN",
        mp: 16,
        mult: 0.85,
        type: "atk",
        tar: "all",
        desc: "ระดมธนูใส่ศัตรูทั้งหมด\n//Volley hits all enemies",
      },
      {
        name: "POISON ARROW",
        mp: 10,
        mult: 0.75,
        type: "atk",
        tar: "one",
        poison: true,
        desc: "ทำให้ติดพิษ 3 เทิร์น\n//Poisons for 3 turns",
      },
    ],
  },
];
