export const SHOP_ITEMS = [
  {
    id: "potion",
    name: "ยาฟื้นฟู / HEALTH POTION",
    d: "ฟื้น HP 60 / Restore 60 HP",
    price: 30,
    type: "item",
  },
  {
    id: "ether",
    name: "อีเธอร์ / ETHER",
    d: "ฟื้น MP 40 / Restore 40 MP",
    price: 40,
    type: "item",
  },
  {
    id: "revive",
    name: "ขนนกฟีนิกซ์ / PHOENIX DOWN",
    d: "ชุบชีวิตพร้อม HP 50%",
    price: 75,
    type: "item",
  },
  {
    id: "up_phetto",
    name: "ลับคมดาบ: IRON SWORD+",
    d: "เพิ่ม ATK ให้เพชรโตะ +12",
    price: 90,
    type: "upgrade",
    target: "phetto",
    amt: 12,
  },
  {
    id: "up_lyra",
    name: "เสริมพลังไม้เท้า: OAK STAFF+",
    d: "เพิ่ม ATK ให้ลีร่า +14",
    price: 110,
    type: "upgrade",
    target: "lyra",
    amt: 14,
  },
  {
    id: "up_riven",
    name: "แต่งสายธนู: ASH BOW+",
    d: "เพิ่ม ATK ให้ริเวน +12",
    price: 90,
    type: "upgrade",
    target: "riven",
    amt: 12,
  },
];
